AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Table mínima para pruebas"

Parameters:
  TableName:
    Type: String
    Default: athletes-table
    Description: DynamoDB table Name

Resources:
  AthletesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: athlete_id
          AttributeType: S
      KeySchema:
        - AttributeName: athlete_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref AthletesTable

  TableArn:
    Description: ARN DynamoDB table
    Value: !GetAtt AthletesTable.Arn
