AWSTemplateFormatVersion: "2010-09-09"
Description: "Tabla DynamoDB para la API de atletas (Versión desacoplada)"

Parameters:
  TableName:
    Type: String
    Default: athletes-table 
    Description: Nombre de la tabla DynamoDB para atletas

Resources:
  AthletesTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: athlete_id 
          AttributeType: N          
      KeySchema:
        - AttributeName: athlete_id 
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: Nombre de la tabla DynamoDB
    Value: !Ref AthletesTable 

  TableArn:
    Description: ARN de la tabla DynamoDB
    Value: !GetAtt AthletesTable.Arn 