AWSTemplateFormatVersion: '2010-09-09'
Description: >
  API Athletes (Desacoplada) con Lambda+Docker y API Key [USA LabRole]
  (Versión Pura de CloudFormation)

Parameters:
  ImageName:
    Type: String
    Description: "El nombre de la imagen en ECR (ej: athletes-lambda-image:latest)"
    Default: "athletes-lambda-image:latest"
  TableName:
    Type: String
    Default: "AthletesTable-Lambda"

Resources:
  PokemonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: athletes_id
          AttributeType: N
      KeySchema:
        - AttributeName: athletes_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 2. El API Gateway
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Athletes-Lambda-API
      EndpointConfiguration:
        Types: [REGIONAL]

  # --- Recursos (Paths) ---
  AthletesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AthletesApi
      ParentId: !GetAtt AthletesApi.RootResourceId
      PathPart: "pokemon"

  AthleteIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AthletesApi
      ParentId: !Ref AthletesResource
      PathPart: "{id}"

  # --- 1. CREATE (POST /pokemon) ---
  CreateAthletesLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pokedex-CreateAthletes
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      ImageConfig:
        Command: ["app.CreateAthlete.handler"]

  CreateAthleteApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePokemonLambda.Arn}/invocations"

  CreatePokemonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreatePokemonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/POST/pokemon"

  # --- 2. GET BY ID (GET /pokemon/{id}) ---
  GetPokemonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pokedex-GetPokemonById
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      ImageConfig:
        Command: ["app.GetPokemon.handler"]

  GetRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPokemonLambda.Arn}/invocations"

  GetPokemonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetPokemonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/GET/pokemon/{id}"

  # --- 3. GET ALL (GET /pokemon) ---
  GetAllPokemonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pokedex-GetAllPokemon
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      ImageConfig:
        Command: ["app.GetAllPokemon.handler"]

  GetAllRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAllPokemonLambda.Arn}/invocations"

  GetAllPokemonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetAllPokemonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/GET/pokemon"

  # --- 4. UPDATE (PUT /pokemon/{id}) ---
  UpdatePokemonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pokedex-UpdatePokemon
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      ImageConfig:
        Command: ["app.UpdatePokemon.handler"]

  UpdateRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonIdResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdatePokemonLambda.Arn}/invocations"

  UpdatePokemonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt UpdatePokemonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/PUT/pokemon/{id}"

  # --- 5. DELETE (DELETE /pokemon/{id}) ---
  DeletePokemonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Pokedex-DeletePokemon
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      ImageConfig:
        Command: ["app.DeletePokemon.handler"]

  DeleteRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonIdResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeletePokemonLambda.Arn}/invocations"

  DeletePokemonLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DeletePokemonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/DELETE/pokemon/{id}"

  # --- 6. OPTIONS (CORS Preflight /pokemon) ---
  OptionsPokemonMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false 
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # --- 7. OPTIONS (CORS Preflight /pokemon/{id}) ---
  OptionsPokemonIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref PokemonIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # --- Despliegue de API ---
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - CreateRestApiMethod
      - GetRestApiMethod
      - GetAllRestApiMethod
      - UpdateRestApiMethod
      - DeleteRestApiMethod
      - OptionsPokemonMethod
      - OptionsPokemonIdMethod
    Properties:
      RestApiId: !Ref RestApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      StageName: Prod
            
  # --- Seguridad (API Key) ---
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: athletes-lambda-api-key
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: athletes-lambda-usage-plan
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: !Ref ApiStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  LambdaAPIEndpoint:
    Description: "Endpoint público de la API Lambda (arquitectura desacoplada)"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pokemon"
    Export:
      Name: LambdaAPIEndpoint

  ApiKeyValue:
    Description: "Valor de la API Key para consumir la API"
    Value: !Ref ApiKey
    Export:
      Name: LambdaAPIKey
